# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66890e73412a74d2b3d289efdccd7ce6c1643e5d4eb98279fff3bdf57d57b9b5b8cae4bef429aa0173ecb31bbdce46744d9bbd8193958dcd1cd0585cb2de5555

test:
  secret_key_base: 749c825c40c3f48cb138394e027ff119960e6c36250af9602b40c18e6a63e31bf37f3d192ff7a4e3ea971d2534186725f6f59bc847d35c294de4fdfb49d9cdce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
